### ISSUE TITLE
Resolving "Your app is having trouble loading the auth0_login_component.ComponentHost component"

### ISSUE THREAD

**Issue by andrei-volkau** [asehmi/Data-Science-Meetup-Oxford#3]
Hi Arvindra, @asehmi 

Many thanks for the project! I would appreciate knowing possible reasons for having the following warning.

<img width="1061" alt="Screenshot 2021-03-03 at 18 35 08" src="https://user-images.githubusercontent.com/12778567/109830078-2fbb5980-7c4f-11eb-9562-203512f0c0ea.png">

I am using the following value for API_BASE_URL

`API_BASE_URL='http://localhost:3001'`

**Comment by ygCoconut** [comment]
Hi @andrei-volkau , I am running into the same issue. How did you solve it ?

Many thanks in advance,
Nils

**Comment by munivinayk** [comment]
Hi @andrei-volkau , I am running into the same issue - please share your solution here. thanks and regards,
Muni

**Comment by bonlime** [comment]
Solution for this problem is to rename `.env.sample` to `.env`. Hope this is helpfull for anyone trying to use this repo in the future
